<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>One Page Website</السفارة العراقية>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-image: url('background.jpg'); /* Replace with your image file */
            background-size: cover;
            background-position: center;
            height: 100vh;
            font-family: Arial, sans-serif;
            color:black;
            text-align: center;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        h1 {
            font-size: 3rem;
        }
        p {
            font-size: 1.5rem;
        }
    </style>
</head>
<body>
    <div>
        <h1>,وكالة خاصة</h1>
        <p>سفارة جمهورية العراق في انقرة
            وكالة خاصة

        </p>
    </div>
</body>
</html>
